### PR TITLE
Allows reading input data which is not in float32 format.

### PR DESCRIPTION
**Pull request by tzickel**
The documentation states that the program can read input of any datatype as long as it's the same one. This is not true. This code is an attempt to fix this

### CODE REVIEW

**Comment by tzickel** [comment]
Had a stupid typo... please remerge that line.

**Comment by giohappy** [comment]
I cant'see it

**Comment by tzickel** [comment]
astype(numpy.float32)**)**.tostring() -> astype(numpy.float32).tostring()

**Comment by giohappy** [comment]
I don't have a pc today, only a smartphone. Can you provide a PR which fix it? I can easily merge it with a phone.

**Pull request merged**
